3a0aa5651843 ("selinux: Return directly after a failed next_entry() in genfs_read()")
